export const links = [
    {
        text: 'Home',
        path: '/',
        active: true
    },
    {
        text: 'Trade',
        path: '/trade'
    },
    {
        text: 'Earn',
        path: '/#section_four_container',
        sectionLink: true
    },
    {
        text: 'Contact',
        path: '/#footer',
        sectionLink: true
    },
]

export const whyChooseUs = [
    {
        image: '/briefcaseclosed.svg',
        heading: 'Proven Expertise',
        text: 'Our Copy Trader Masters have a track record of success, ensuring you gain from their experience and expertise.'
    },
    {
        image: '/briefcaseopen.svg',
        heading: 'Effortless Trading',
        text: 'No need for extensive research or strategy development replicate the trades of top traders and watch your investments grow.'
    },
    {
        image: '/keybig.svg',
        heading: 'Lucrative Referral Program',
        text: 'Earn commissions by inviting others to join Universal FX, adding an extra stream of income to your trading profits.'
    },
]

export const reviews = [
    {
        stars: 5,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/Usama.jpg',
        name: 'Usama'
    },
    {
        stars: 4,
        text: '"As someone new to trading, Universal FX has made it incredibly easy. The Copy Trader Masters are like having my own personal trading team. I love watching my profits grow with minimal effort."',
        image: '/Manish.jpg',
        name: 'Manish'
    },
    {
        stars: 4,
        text: '"Universal FX is my secret weapon for generating passive income. The Copy Trader Masters consistently deliver profitable trades, and the referral program sweetens the deal even more."',
        image: '/Ali.jpg',
        name: 'Ali Sethi'
    },
    {
        stars: 4,
        text: '"Not only is Universal FX a fantastic platform for earning, but it also has a great community feel. The referral program encourages collaboration, and it\'s rewarding to share the success with others."',
        image: '/Vijay.jpg',
        name: 'Vijay'
    },
    {
        stars: 5,
        text: '"As a busy professional, I don\'t have time to research trades. Universal FX solves that problem. The Copy Trader Masters do the heavy lifting, allowing me to focus on my career while still earning from trading."',
        image: '/Khaleel.jpg',
        name: 'Khaleel'
    },
    {
        stars: 5,
        text: '"I\'m not a financial expert, but Universal FX makes it easy for anyone to succeed. The Copy Trader Masters are the real deal, and the platform\'s intuitive design makes everything seamless. Love the passive income!"',
        image: '/Umer.jpg',
        name: 'Mr Umer'
    },
    {
        stars: 4,
        text: '"If you\'re looking for a way to make passive income with minimal effort, Universal FX is the answer. The Copy Trader Masters are brilliant, and the platform is top-notch. Don\'t miss out!"',
        image: '/Sajda.jpg',
        name: 'Sajda'
    },
    // {
    //     stars: 5,
    //     text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
    //     image: '/adams.svg',
    //     name: 'Adam Lewis 8'
    // },

]

export const questions = [
    {
        id: 1,
        heading: 'What is Copy Trading and how does it work with Universal FX?',
        content:
            'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
        status: false,
    },
    {
        id: 2,
        heading: 'What types of income can I earn with Universal FX?',
        content:
            'With Universal FX, you can earn two types of income: Individual Earnings and Referral Commissions. Individual Earnings come from the profits generated by copying the trades of our expert traders. Referral Commissions are earned by referring others to the platform, with 10% commission on direct referrals and 5% on indirect referrals.',
        status: false,
    },
    {
        id: 3,
        heading: ' How do I start Copy Trading with Universal FX?',
        content:
            'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
        status: false,
    },
]